name = "publume-scheduler"
main = "worker.js"
compatibility_date = "2026-08-05"
workers_dev = false

[triggers]
crons = ["50 23 * * *"]

[observability]
enabled = true

[secrets]
required = ["GITHUB_TOKEN"]
